### ISSUE TITLE
Missing Pagani_ZondaCinqueCoupe_2009

### ISSUE THREAD

**Issue by tattdogg** [Nitro4CSR/CSR2-DataBase#10]
Hi

Pagani_ZondaCinqueCoupe_2009 ([1.Cars/1.Stock/2.Purple Star/Pagani/Pagani Zonda Cinque](https://github.com/Nitro4CSR/CSR2-DataBase/tree/Everything/1.Cars/1.Stock/2.Purple%20Star/Pagani/Pagani%20Zonda%20Cinque)) was removed in ccf6909

It shoud be added back or removed from [#AllCarCRDBs.txt](https://github.com/Nitro4CSR/CSR2-DataBase/blob/Everything/1.Cars/%23AllCarCRDBs.txt)

**Comment by Nitro4CSR** [comment]
Thank you for pointing it out I'll add the files back in later today
