### ISSUE TITLE
Overfused RAM 1500 TRX

### ISSUE THREAD

**Issue by NiiTRooX** [Nitro4CSR/CSR2-DataBase#3]
**File**
The maxed RAM 1500 TRX is overfused.

I believe all variants have this problem.

**Address**
[CSR2-DataBase/1.Cars/Update 4.0.0/2.Maxed/1.Gold Star/RAM/RAM 1500 TRX/](https://github.com/Nitro4CSR/CSR2-DataBase/tree/Everything/1.Cars/Update%204.0.0/2.Maxed/1.Gold%20Star/RAM/RAM%201500%20TRX)

**Expected behavior**
"upst" has to be T4 maxout

**Screenshots**
![ingame screenshot](https://i.imgur.com/H61ERO2.png)

**Comment by NiiTRooX** [comment]
readme has a wrong fusion count, too.
Should be 91
![](https://camo.githubusercontent.com/9d5b28a0905092e4e0091dc098e417a229011c686644dd3c5e1f3fc0a48aa9e6/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3930343032343338303337303232333131342f3938393233333939313737313039393136362f342e302e302e706e673f73697a653d34303936)

**Comment by Nitro4CSR** [comment]
Hey thanks for pointing ou to the problems
We are actively working on a fix and could already resolve the wrong fusions on the car files
A fix for the Readme will follow quickly.

Thanks for your patience

**Comment by NiiTRooX** [comment]
Thank you for updating so soon,
in case you didn't notice the  "msou" also should be lowered to 3009000.

**Comment by Nitro4CSR** [comment]
Thanks for the tip I will double check tomorrow

**Comment by Nitro4CSR** [comment]
Everything has been fixed and double checked.
We thank You for your effort and hope You have a nice day
