### ISSUE TITLE
Maserati_MC20_2021

### ISSUE THREAD

**Issue by tattdogg** [Nitro4CSR/CSR2-DataBase#7]
**File**
`#AllCarCRDBs.txt`

**Address**
1. Go to '1.Cars' directory

**Expected behavior**
Missed `Maserati_MC20_2021` (gold card)? It only has `Maserati_MC20Coupe_2021` (purple car)

**Comment by Nitro4CSR** [comment]
The gold star Mc20 got replaced with the purple star one
There no longer is a gold star version available
