### ISSUE TITLE
folders to merge

### ISSUE THREAD

**Issue by tattdogg** [Nitro4CSR/CSR2-DataBase#8]
These 2 folders need to be merged:
https://github.com/Nitro4CSR/CSR2-DataBase/tree/Everything/1.Cars/1.Stock/1.Gold%20Star/McLaren/McLaren%20P1
https://github.com/Nitro4CSR/CSR2-DataBase/tree/Everything/1.Cars/1.Stock/1.Gold%20Star/McLaren/Mclaren%20P1

`Mclaren P1` contains only `jpg` files
`McLaren P1` contains only `txt` files

**Comment by Kustomz** [comment]
Looking into it now. 👍

**Comment by Kustomz** [comment]
Issue fixed credit to Nitro.
